name: CI CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  sonarqube:
    name: Sonarqube Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    outputs:
      sonarcloud_output: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}

  opa:
    name: "🚧 Unit tests gate"
    runs-on: ubuntu-latest
    needs:
      - sonarqube
    steps:
      - name: "⏳ Validate quality using OPA"
        uses: OpsVerseIO/opa-policy-check@0.1.0
        with:
          opaServerUrl: "http://opa-opsverse.int.devopsnow.io"
          opaServerAuthToken: ${{ secrets.OPA_SERVER_AUTH_TOKEN }}
          opaServerInput: '{"input": null}'
          opaServerPackageName: "example/include"

  opa-code-coverage:
    name: "🚧 Code coverage gate"
    runs-on: ubuntu-latest
    needs:
      - sonarqube
    steps:
      - name: "⏳ Validate quality using OPA"
        uses: OpsVerseIO/opa-policy-check@0.2.0
        with:
          opaServerUrl: "http://opa-opsverse.int.devopsnow.io"
          opaServerAuthToken: ${{ secrets.OPA_SERVER_AUTH_TOKEN }}
          opaServerInput: '{"input": null}'
          opaServerPackageName: "example/include"
          skipTlsValidation: true

  opa-sonarqube:
    name: "🚧 Static code analysis gate"
    runs-on: ubuntu-latest
    needs:
      - sonarqube
    steps:
      - name: "⏳ Validate quality using OPA"
        uses: OpsVerseIO/opa-policy-check@0.2.0
        with:
          opaServerUrl: "http://opa-opsverse.int.devopsnow.io"
          opaServerAuthToken: ${{ secrets.OPA_SERVER_AUTH_TOKEN }}
          opaServerInput: '{"input": null}'
          opaServerPackageName: "example/include"
          skipTlsValidation: true

  build:
    name: "📦 Build docker image and push to Amazon ECR"
    runs-on: ubuntu-latest
    env:
      APP_NAME: hello-world-api-dotnet
    needs:
      - sonarqube
      - opa
      - opa-code-coverage
      - opa-sonarqube
    timeout-minutes: 10
    steps:
      - name: "🔧 Add dynamic envs"
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "SHA= ${GITHUB_SHA}"
          echo "SHORT SHA= ${SHORT_SHA}"

      - name: "☁️ checkout repository"
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: "🔒 Login to Amazon ECR 🔓"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: "📦📂 Build, tag, and push docker image to Amazon ECR"
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "hello-world-api-dotnet"
          IMAGE_TAG: ${{ env.SHORT_SHA }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  update-image-stage:
    name: "📝 Update STAGE image tag"
    runs-on: ubuntu-latest
    needs:
      - sonarqube
      - opa
      - opa-code-coverage
      - opa-sonarqube
      - build
    timeout-minutes: 10
    steps:
      - name: "🔧 Add dynamic envs"
        id: "image-tag"
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "SHA= ${GITHUB_SHA}"
          echo "SHORT SHA= ${SHORT_SHA}"
          echo "::set-output name=version::$SHORT_SHA"

      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: "OpsVerseIO/deployment-manifests"
          path: main
          token: ${{ secrets.GH_PAT }}

      - name: "📝 Update Image tag Version in the DEV manifest file"
        uses: OpsVerseIO/image-updater-action@0.1.0
        with:
          repository: "OpsVerseIO/deployment-manifests"
          valueFile: 'hello-world-api-dotnet/helm/stage/values.yaml'
          propertyPath: 'helloworldapidotnet.image.tag'
          value: '${{ env.SHORT_SHA }}'
          branch: main
          createPR: false
          message: '[STAGE] Update Image tag of hello-world-api-dotnet'
          token: ${{ secrets.GH_PAT }}
          workDir: main
          masterBranchName: main
          targetBranch: main
          force: true
          updateFile: true

  release-stage:
    name: "🚀 Deploy to STAGE (ArgoCD Sync)"
    runs-on: ubuntu-latest
    needs:
      - sonarqube
      - opa
      - opa-code-coverage
      - opa-sonarqube
      - build
      - update-image-stage
    timeout-minutes: 10
    steps:
      - name: "🔧 Trigger ArgoCD Sync/Deployment in STAGE"
        uses: opsverseio/argocd-sync@0.2.0
        with:
          address: ${{ secrets.ARGOCD_SERVER }}
          token: ${{ secrets.ARGOCD_TOKEN }}
          action: sync
          appName: ${{ secrets.ARGOCD_PROD_APP_NAME }}
          disableTlsVerification: "true"

      - name: "🚀 Deploy to STAGE"
        run: |
            echo "⏳ Deploying the application to STAGE"
            echo "🚀✅💚 Successfully synced STAGE ArgoCD and deployed the application to STAGE"

  integration-test:
    name: "🚨 Run integration test suite"
    needs:
      - sonarqube
      - opa
      - opa-code-coverage
      - opa-sonarqube
      - build
      - release-stage
    runs-on: ubuntu-latest
    steps:
      - name: "📩📨 Message from Open Policy Agent (OPA) Server"
        run: |
          echo "Running integration test suite"
          echo "⌛ Connecting to STAGE application at: https://staging-server.opsverse.io"
          echo "✅💚 Integration tests passed"         

  integration-test-opa:
    name: "🚧 Integration tests gate"
    needs:
      - sonarqube
      - opa
      - opa-code-coverage
      - opa-sonarqube
      - build
      - release-stage
      - integration-test
    runs-on: ubuntu-latest 
    steps:
      - name: "⏳ Validate quality using OPA"
        uses: OpsVerseIO/opa-policy-check@0.2.0
        with:
          opaServerUrl: "https://opa-opsverse.int.devopsnow.io"
          opaServerAuthToken: ${{ secrets.OPA_SERVER_AUTH_TOKEN }}
          opaServerInput: '{"input": null}'
          opaServerPackageName: "example/include"
          skipTlsValidation: true

  update-image-prod:
    name: "📝 Update prod image tag"
    runs-on: ubuntu-latest
    needs:
      - sonarqube
      - opa
      - opa-code-coverage
      - opa-sonarqube
      - build
      - release-stage
      - integration-test
      - integration-test-opa
    timeout-minutes: 10
    steps:
      - name: "🔧 Add dynamic envs"
        id: "image-tag"
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "SHA= ${GITHUB_SHA}"
          echo "SHORT SHA= ${SHORT_SHA}"
          echo "::set-output name=version::$SHORT_SHA"

      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: "OpsVerseIO/deployment-manifests"
          path: main
          token: ${{ secrets.GH_PAT }}

      - name: "📝 Update Image tag Version in the PROD manifest file"
        uses: OpsVerseIO/image-updater-action@0.1.0
        with:
          repository: "OpsVerseIO/deployment-manifests"
          valueFile: 'hello-world-api-dotnet/helm/prod/values.yaml'
          propertyPath: 'helloworldapidotnet.image.tag'
          value: '${{ env.SHORT_SHA }}'
          branch: main
          createPR: false
          message: '[PROD] Update Image tag of hello-world-api-dotnet'
          token: ${{ secrets.GH_PAT }}
          workDir: main
          masterBranchName: main
          targetBranch: main
          force: true
          updateFile: true

  release-prod:
    environment:
      name: production
    name: "🚀 Deploy to PROD (ArgoCD Sync)"
    needs:
      - sonarqube
      - opa
      - opa-code-coverage
      - opa-sonarqube
      - build
      - release-stage
      - integration-test
      - integration-test-opa
      - update-image-prod
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "🔧 Trigger ArgoCD Sync/Deployment in PROD"
        uses: opsverseio/argocd-sync@0.2.0
        with:
          address: ${{ secrets.ARGOCD_SERVER }}
          token: ${{ secrets.ARGOCD_TOKEN }}
          action: sync
          appName: ${{ secrets.ARGOCD_PROD_APP_NAME }}
          disableTlsVerification: "true"

      - name: "🚀 Deploy to PROD ENV"
        run: |
          echo "⏳ Deploying the application to PROD"
          echo "🚀✅💚 Successfully synced PROD ArgoCD and deployed the application to PROD"

  cleanup:
    name: "♻️ Cleanup actions"
    needs:
      - release-stage
      - release-prod
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "♻️ remove build artifacts"
        run: |
          echo "♻️ Cleaning up the build artifacts"
          echo "♻️✅ Successfully cleaned up the build artifacts"
